### ISSUE TITLE
한꺼번에 많은 파일을 업로드 했을 때 related tags목록 생성에 많은 시간이 걸리는 문제

### ISSUE THREAD

**Issue by yujonglee** [yujong-lee/tagging-back#1]
각 4개의 태그를 가진 91개의 문서의 테스트 데이터에 대하여  related tags목록 생성에 약 1분의 시간이 소요됨.
DB에 반복적으로 findOne과 save요청을 보내는 것이 오버헤드의 원인으로 보이므로 서버에서 먼저 전처리를 한 뒤 한번에 DB에 넣는 것이 필요해보임.

tag.service.ts, document.service.ts 파일 참고.

**Comment by yujong-lee** [comment]
테스트

**Comment by Parksy-00** [comment]
save()에 있는 await을 제거했더니 시간이 절반가량 줄었음. 근데 이게 related가 제대로 저장이되고있는건지 확인해봐야할 것 같음

**Comment by yujonglee** [comment]
더 이상 relateTags를 생성하지 않는 것으로 계획이 변경되어 close함.
